title:             My Blog
email:             93stw@naver.com
description:       여러분들의 흥미와 관심사를 빅데이터로 수집하여 높은 조회수를 기록할 만한 제목을 도출하였습니다.
author:            Start Bootstrap
baseurl:           ""
url:               "https://momentum1993.github.io"
disqus_url:        "http://disqus.com/by/momentum1993"
disqus_shortname:         momentum1993


# Social Profiles
twitter_username:  
github_username:   momentum1993
facebook_username: 

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
