title:             T.U Blog
email:             93stw@naver.com
description:       초보 프로그래머의 공간입니다.
author:            T.U. Shin
baseurl:           ""
url:               "https://momentum1993.github.io"
disqus_shortname: momentum1993

# Font
font_heading:        "'Roboto Slab', 'Nanum Gothic', Helvetica, Arial, sans-serif"
# The text font. Expects a string that is a valid CSS font-family value.
font:                "'Noto Sans', 'Nanum Gothic', Helvetica, Arial, sans-serif"
# The string encoding what fonts to fetch from Google Fonts.
# See: https://qwtel.com/hydejack/docs/configuration/
google_fonts:        Roboto+Slab:700|Noto+Sans:400,400i,700,700i

# Social Profiles
twitter_username:  
github_username:   momentum1993
facebook_username: 

# Build settings
markdown:          kramdown
permalink:	   pretty
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  
# add
category_dir: category/
tag_dir: tag/
