title:             T.U Blog
email:             93stw@naver.com
description:       초보 프로그래머의 공간입니다.
author:            T.U. Shin
baseurl:           ""
url:               "https://momentum1993.github.io"
disqus_shortname: momentum1993

# Social Profiles
twitter_username:  
github_username:   momentum1993
facebook_username: 

# Build settings
markdown:          kramdown
permalink:	   pretty
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  
# add
category_dir: category/
tag_dir: tag/
